Update main.yml to be able deploy even with Lint warnings

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,7 +29,8 @@ jobs:
         run: npm ci
 
       - name: Run ESLint (Linting)
-        run: npx eslint . --max-warnings=0
+        continue-on-error: true  # Allow the workflow to continue even if ESLint fails
+        run: npx eslint . || true  # Prevents failure from stopping the workflow
 
       - name: Run Prettier (Check Formatting)
         run: npx prettier --check .
